Adding user is implemented
ant-media/ManagementConsole_WebApp pull request #72
Opened 2021-02-15 12:37 UTC by golgetahir

2021-03-08 12:37 UTC, mekya requested changes
Change the write path and add filter.

2021-03-08 12:37 UTC, mekya commented on src/main/java/io/antmedia/console/datastore/MongoStore.java
> +	public List<User> getUserList(){
Why it returns null?

2021-03-08 12:37 UTC, mekya commented on src/main/java/io/antmedia/console/rest/RestService.java
> +		if(isAuthenticated(session)) {
I think it will be good if we have a filter for checking the authentication?

I mean make every edit/update operations under write/ path and create a filter for that in the web.xml

2021-03-10 09:15 UTC, golgetahir commented on src/main/java/io/antmedia/console/rest/RestService.java
> +		if(isAuthenticated(session)) {
Done.

2021-03-10 09:15 UTC, golgetahir commented on src/main/java/io/antmedia/console/datastore/MongoStore.java
> +	public List<User> getUserList(){
Implemented.

2021-03-22 16:11 UTC, mekya reviewed
Please check the new commits

2021-03-22 17:45 UTC, mekya approved these changes

2021-05-26 18:59 UTC, merged